#设置配置文件的加载，开发环境：dev,生成环境：prod
spring:
  profiles:
    active: prod
  #设置controller返回，过滤字段为空的内容
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 800MB
 
#文件服务器路径
uploadsPath:
  scriptPath: /opt/appFile/script/
  coreFilePath: /opt/appFile/coreFile/
  ipaPath: /opt/appFile/ipa/
  cpaScript: /opt/appFile/cpaScript/
